### ISSUE TITLE
Second processor not detected (working) in release 22.03.20

### ISSUE THREAD

**Issue by EeGeez** [sharpie7/BeebFpga_MiSTer#1]
Recently came this very welcome version. No second processor though
Thank you

Edit: Used the other 22.03.20 and all is well. Sorry

**Comment by sharpie7** [comment]
Yes, the version with the debugger doesn't have a second processor.

**Comment by EeGeez** [comment]
Understood.
Thank you for clarification and for adding to the Mister BBC Core
